/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package señordelatienda;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Registro extends javax.swing.JFrame {
public static Scanner Sc ;

Seguridad S = new Seguridad();
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        marco = new javax.swing.JPanel();
        jbn_SAlir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_NuevoUsusario = new javax.swing.JTextField();
        txt_NuevaContra = new javax.swing.JTextField();
        jbn_AgregarUsuario = new javax.swing.JButton();
        btn_LimpiarRegistro = new javax.swing.JButton();
        SeñorTienda = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jbn_SAlir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar (2).png"))); // NOI18N
        jbn_SAlir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_SAlirActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/candado.png"))); // NOI18N

        jLabel7.setText("Nombre del usuario:");

        jLabel8.setText("Ingrese una contraseña:");

        txt_NuevoUsusario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NuevoUsusarioKeyTyped(evt);
            }
        });

        txt_NuevaContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NuevaContraKeyTyped(evt);
            }
        });

        jbn_AgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add-file.png"))); // NOI18N
        jbn_AgregarUsuario.setText("AGREGAR");
        jbn_AgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_AgregarUsuarioActionPerformed(evt);
            }
        });

        btn_LimpiarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/escoba.png"))); // NOI18N
        btn_LimpiarRegistro.setText("LIMPIAR");
        btn_LimpiarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarRegistroActionPerformed(evt);
            }
        });

        SeñorTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sds.png"))); // NOI18N

        javax.swing.GroupLayout marcoLayout = new javax.swing.GroupLayout(marco);
        marco.setLayout(marcoLayout);
        marcoLayout.setHorizontalGroup(
            marcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marcoLayout.createSequentialGroup()
                .addGroup(marcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(marcoLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(24, 24, 24)
                        .addComponent(txt_NuevoUsusario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(marcoLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8)
                        .addGap(11, 11, 11)
                        .addComponent(txt_NuevaContra, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(marcoLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jbn_AgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btn_LimpiarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(marcoLayout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(SeñorTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbn_SAlir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        marcoLayout.setVerticalGroup(
            marcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marcoLayout.createSequentialGroup()
                .addGroup(marcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(marcoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(SeñorTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbn_SAlir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(marcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(marcoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(marcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txt_NuevoUsusario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(marcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(marcoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addComponent(txt_NuevaContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(marcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbn_AgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LimpiarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 810, 410));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/065580938b36e4c049ec033745248216.jpg"))); // NOI18N
        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbn_SAlirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_SAlirActionPerformed
       Login L = new Login();
       L.setVisible(true);
    }//GEN-LAST:event_jbn_SAlirActionPerformed

    private void btn_LimpiarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarRegistroActionPerformed
        txt_NuevaContra.setText("");
        txt_NuevoUsusario.setText("");
    }//GEN-LAST:event_btn_LimpiarRegistroActionPerformed

    private void txt_NuevoUsusarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NuevoUsusarioKeyTyped
                char c = evt.getKeyChar();
        if ((c < '0' || c > '9')&&(c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<'_')&&(c<'-')&&(c<'.')&&(c<'@')&&(c<'+') ){
            evt.consume();
        }
    }//GEN-LAST:event_txt_NuevoUsusarioKeyTyped

    private void txt_NuevaContraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NuevaContraKeyTyped
                        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')&&(c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<'_')&&(c<'-')&&(c<'.')&&(c<'@')&&(c<'+') ){
            evt.consume();
        }
    }//GEN-LAST:event_txt_NuevaContraKeyTyped

    private void jbn_AgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_AgregarUsuarioActionPerformed
 if (txt_NuevoUsusario.getText().length() == 0 && txt_NuevaContra.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese un Usuario y/o Contraseña valido");
        } else {
     String usu = (txt_NuevoUsusario.getText());
     String pwd = (txt_NuevaContra.getText());
      S.Registrar(txt_NuevoUsusario.getText(), txt_NuevaContra.getText());
      JOptionPane.showMessageDialog(null, "Usuario Agregado Correctamente");
      Login L = new Login();
      L.setVisible(true);
 }
    }//GEN-LAST:event_jbn_AgregarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SeñorTienda;
    private javax.swing.JButton btn_LimpiarRegistro;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbn_AgregarUsuario;
    private javax.swing.JButton jbn_SAlir;
    private javax.swing.JPanel marco;
    private javax.swing.JTextField txt_NuevaContra;
    private javax.swing.JTextField txt_NuevoUsusario;
    // End of variables declaration//GEN-END:variables
}
